import {
  TopicItem,
  RolePlayScenario,
  ExerciseItem,
  LearningHistoryRecord,
  DailyStatisticRecord,
  UserProfile,
} from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'user-default-1',
  fullName: 'Nguyễn Minh Quân',
  email: 'minhquan.english@school.edu.vn',
  gradeLevel: 'Lớp 9A - THCS Đoàn Thị Điểm',
  proficiencyLevel: 'Intermediate',
  dailyGoalMinutes: 30,
  dailyGoalScore: 85,
  currentStreak: 7,
  longestStreak: 14,
  totalXp: 1450,
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  useMockAI: true,
};

// 17 Chủ đề thực tế theo yêu cầu
export const TOPICS_LIST: TopicItem[] = [
  {
    id: 'introduce-yourself',
    title: 'Introduce yourself',
    titleVi: 'Giới thiệu bản thân',
    description: 'Chia sẻ về tên tuổi, quê quán, tính cách và ước mơ của bạn.',
    icon: 'UserCheck',
    category: 'Daily Life',
    recommendedLevel: 'Beginner',
  },
  {
    id: 'family',
    title: 'Family',
    titleVi: 'Gia đình thân yêu',
    description: 'Miêu tả các thành viên trong gia đình, nghề nghiệp và thói quen sum họp.',
    icon: 'Users',
    category: 'Daily Life',
    recommendedLevel: 'Beginner',
  },
  {
    id: 'school',
    title: 'School',
    titleVi: 'Trường học & Thầy cô',
    description: 'Nói về môn học yêu thích, bạn bè, thầy cô và hoạt động ngoại khóa.',
    icon: 'GraduationCap',
    category: 'School & Work',
    recommendedLevel: 'Beginner',
  },
  {
    id: 'friends',
    title: 'Friends',
    titleVi: 'Tình bạn bè',
    description: 'Kể về người bạn thân nhất, kỷ niệm đáng nhớ và sự sẻ chia trong cuộc sống.',
    icon: 'HeartHandshake',
    category: 'Daily Life',
    recommendedLevel: 'Beginner',
  },
  {
    id: 'hobbies',
    title: 'Hobbies',
    titleVi: 'Sở thích & Đam mê',
    description: 'Chia sẻ về thể thao, âm nhạc, vẽ tranh hoặc những điều bạn làm lúc rảnh.',
    icon: 'Sparkles',
    category: 'Daily Life',
    recommendedLevel: 'Beginner',
  },
  {
    id: 'food',
    title: 'Food & Cooking',
    titleVi: 'Ẩm thực & Nấu nướng',
    description: 'Món ăn truyền thống, đồ ăn vặt yêu thích và cách chế biến món đơn giản.',
    icon: 'Utensils',
    category: 'Daily Life',
    recommendedLevel: 'Beginner',
  },
  {
    id: 'shopping',
    title: 'Shopping',
    titleVi: 'Mua sắm & Giá cả',
    description: 'Hỏi giá, mặc cả, chọn size quần áo và mua đồ tại siêu thị, trung tâm thương mại.',
    icon: 'ShoppingBag',
    category: 'Daily Life',
    recommendedLevel: 'Intermediate',
  },
  {
    id: 'restaurant',
    title: 'Restaurant',
    titleVi: 'Nhà hàng & Gọi món',
    description: 'Đặt bàn, gọi món ăn, yêu cầu phục vụ và thanh toán hóa đơn bằng tiếng Anh.',
    icon: 'Coffee',
    category: 'Travel & Social',
    recommendedLevel: 'Intermediate',
  },
  {
    id: 'travel',
    title: 'Travel',
    titleVi: 'Du lịch & Khám phá',
    description: 'Kể về chuyến đi yêu thích, danh lam thắng cảnh và văn hóa các vùng miền.',
    icon: 'Compass',
    category: 'Travel & Social',
    recommendedLevel: 'Intermediate',
  },
  {
    id: 'asking-directions',
    title: 'Asking for directions',
    titleVi: 'Hỏi & Chỉ đường',
    description: 'Cách hỏi đường tới nhà ga, bệnh viện, bảo tàng và hiểu chỉ dẫn chỉ đường.',
    icon: 'MapPin',
    category: 'Travel & Social',
    recommendedLevel: 'Intermediate',
  },
  {
    id: 'at-airport',
    title: 'At the airport',
    titleVi: 'Tại sân bay',
    description: 'Làm thủ tục check-in, qua cửa an ninh, hỏi cổng lên máy bay và hành lý.',
    icon: 'Plane',
    category: 'Travel & Social',
    recommendedLevel: 'Intermediate',
  },
  {
    id: 'at-hotel',
    title: 'At the hotel',
    titleVi: 'Tại khách sạn',
    description: 'Nhận phòng, trả phòng, yêu cầu dịch vụ phòng và xử lý các vấn đề phát sinh.',
    icon: 'Building2',
    category: 'Travel & Social',
    recommendedLevel: 'Intermediate',
  },
  {
    id: 'health',
    title: 'Health & Wellbeing',
    titleVi: 'Sức khỏe & Lối sống lành mạnh',
    description: 'Kể về triệu chứng bệnh thông thường, thăm khám bác sĩ và giữ gìn thể lực.',
    icon: 'Activity',
    category: 'Daily Life',
    recommendedLevel: 'Intermediate',
  },
  {
    id: 'environment',
    title: 'Environment',
    titleVi: 'Bảo vệ môi trường',
    description: 'Thảo luận về biến đổi khí hậu, tái chế rác thải và năng lượng xanh.',
    icon: 'Leaf',
    category: 'Global & Tech',
    recommendedLevel: 'Advanced',
  },
  {
    id: 'technology',
    title: 'Technology & AI',
    titleVi: 'Công nghệ & Trí tuệ nhân tạo',
    description: 'Ứng dụng công nghệ trong học tập, mạng xã hội và tác động của AI trong tương lai.',
    icon: 'Cpu',
    category: 'Global & Tech',
    recommendedLevel: 'Advanced',
  },
  {
    id: 'future-plans',
    title: 'Future plans',
    titleVi: 'Kế hoạch tương lai',
    description: 'Mục tiêu đại học, du học, nghề nghiệp mơ ước và các dự định 5 năm tới.',
    icon: 'Calendar',
    category: 'School & Work',
    recommendedLevel: 'Advanced',
  },
  {
    id: 'job-interview',
    title: 'Job interview',
    titleVi: 'Phỏng vấn xin việc',
    description: 'Trả lời các câu hỏi phỏng vấn chuẩn quốc tế, thể hiện điểm mạnh và kinh nghiệm.',
    icon: 'Briefcase',
    category: 'School & Work',
    recommendedLevel: 'Advanced',
  },
];

// Chế độ Role-play thực tế
export const ROLE_PLAY_SCENARIOS: RolePlayScenario[] = [
  {
    id: 'rp-restaurant',
    title: 'At a Restaurant',
    titleVi: 'Tại nhà hàng',
    aiRole: 'Friendly Waiter',
    userRole: 'Customer',
    context: 'Bạn đang vào một nhà hàng sang trọng. Người phục vụ tiến lại chào và đưa thực đơn cho bạn.',
    initialMessage: 'Good evening and welcome to The Garden Bistro! A table for one, or are more guests joining you tonight?',
    suggestedPhrases: [
      'Just a table for one, please.',
      'Could I see the dinner menu?',
      'What do you recommend as the house specialty?',
      'Could I have a glass of iced water to start with?'
    ],
    icon: 'Utensils',
  },
  {
    id: 'rp-airport',
    title: 'At the Airport Check-in',
    titleVi: 'Tại quầy làm thủ tục sân bay',
    aiRole: 'Airline Check-in Agent',
    userRole: 'Passenger flying to Singapore',
    context: 'Bạn đang đứng trước quầy thủ tục của hãng hàng không chuẩn bị cho chuyến bay quốc tế.',
    initialMessage: 'Good afternoon! Welcome to SkyWings Airlines. May I please see your passport and flight confirmation?',
    suggestedPhrases: [
      'Here is my passport and electronic ticket.',
      'I would love a window seat if available.',
      'How many pieces of luggage can I check in?',
      'Which gate will my flight depart from?'
    ],
    icon: 'Plane',
  },
  {
    id: 'rp-shopping',
    title: 'Shopping at Clothing Store',
    titleVi: 'Mua sắm tại cửa hàng thời trang',
    aiRole: 'Helpful Sales Assistant',
    userRole: 'Shopper',
    context: 'Bạn đang tìm kiếm một chiếc áo khoác ấm và một vài món quà lưu niệm.',
    initialMessage: 'Hi there! Welcome to Urban Style. Are you looking for anything specific today, or would you like to browse our new collection?',
    suggestedPhrases: [
      'I am looking for a warm jacket for the winter season.',
      'Do you have this in medium size?',
      'Can I try this on in the fitting room?',
      'Is there any discount on this item?'
    ],
    icon: 'ShoppingBag',
  },
  {
    id: 'rp-directions',
    title: 'Asking for Directions in London',
    titleVi: 'Hỏi đường tại London',
    aiRole: 'Friendly Local Londoner',
    userRole: 'Lost Tourist',
    context: 'Bạn bị lạc ở trung tâm thành phố và cần tìm đường đi đến Bảo tàng Quốc gia.',
    initialMessage: 'Hello! You look a bit lost with that city map. Can I help you find your way around?',
    suggestedPhrases: [
      'Excuse me, could you tell me how to get to the British Museum?',
      'Is it within walking distance from here?',
      'Which tube station or bus line should I take?',
      'Thank you so much for your kind help!'
    ],
    icon: 'MapPin',
  },
  {
    id: 'rp-hotel',
    title: 'At the Hotel Reception',
    titleVi: 'Tại quầy lễ tân khách sạn',
    aiRole: 'Front Desk Receptionist',
    userRole: 'Hotel Guest',
    context: 'Bạn vừa tới khách sạn sau một chuyến bay dài và muốn làm thủ tục nhận phòng.',
    initialMessage: 'Good afternoon, sir/madam. Welcome to Grand Horizon Hotel. How can I assist you with your stay today?',
    suggestedPhrases: [
      'I have a reservation under the name Nguyen Minh Quan.',
      'What time is breakfast served tomorrow morning?',
      'Could you provide the Wi-Fi password for guests?',
      'Is room service available 24/7?'
    ],
    icon: 'Building2',
  },
  {
    id: 'rp-interview',
    title: 'Job / Internship Interview',
    titleVi: 'Phỏng vấn học bổng / Việc làm',
    aiRole: 'Senior HR Interviewer',
    userRole: 'Candidate',
    context: 'Bạn đang tham gia buổi phỏng vấn xin học bổng tiếng Anh hoặc vị trí tình nguyện viên quốc tế.',
    initialMessage: 'Welcome to our interview session. Thank you for your interest. To begin, could you briefly introduce yourself and share why you are passionate about this opportunity?',
    suggestedPhrases: [
      'Good morning. It is a pleasure to meet you today.',
      'My name is Quan, and I have always been deeply passionate about communication.',
      'One of my greatest strengths is problem-solving and teamwork.',
      'I believe this opportunity aligns perfectly with my academic goals.'
    ],
    icon: 'Briefcase',
  },
];

// Kho bài tập phong phú đủ 10 dạng
export const SEED_EXERCISES: ExerciseItem[] = [
  // 1. Multiple Choice (School / Grammar)
  {
    id: 'ex-mc-1',
    title: 'School Life & Present Tenses',
    topicId: 'school',
    topicTitle: 'School',
    level: 'Intermediate',
    type: 'multiple_choice',
    questions: [
      {
        id: 'q-mc-1',
        questionOrder: 1,
        questionText: 'My brother usually ______ his homework right after returning from school.',
        type: 'multiple_choice',
        options: ['do', 'does', 'doing', 'did'],
        correctAnswer: 'does',
        explanation: 'Chủ ngữ "My brother" là ngôi thứ ba số ít, có từ nhận biết "usually" (thì hiện tại đơn) -> chọn "does".',
        hint: 'Nhận biết trạng từ tần suất "usually" và chủ ngữ số ít.',
      },
      {
        id: 'q-mc-2',
        questionOrder: 2,
        questionText: 'Which subject deals with the study of living organisms and cells?',
        type: 'multiple_choice',
        options: ['Physics', 'Chemistry', 'Biology', 'Geography'],
        correctAnswer: 'Biology',
        explanation: '"Biology" là môn Sinh học, nghiên cứu về các sinh vật sống và tế bào.',
        hint: 'Từ bắt đầu bằng tiền tố "Bio-" có nghĩa là sự sống.',
      },
      {
        id: 'q-mc-3',
        questionOrder: 3,
        questionText: 'Our school library ______ over 20,000 reference books and magazines.',
        type: 'multiple_choice',
        options: ['contains', 'containing', 'is contain', 'have contained'],
        correctAnswer: 'contains',
        explanation: 'Động từ chỉ trạng thái sở hữu/chứa đựng "contain" dùng ở thì hiện tại đơn với chủ ngữ số ít là "contains".',
        hint: 'Thư viện trường (danh từ số ít) diễn tả sự thật hiển nhiên.',
      },
      {
        id: 'q-mc-4',
        questionOrder: 4,
        questionText: 'Students are encouraged to ______ in volunteer clubs to develop soft skills.',
        type: 'multiple_choice',
        options: ['participate', 'attend', 'arrive', 'join into'],
        correctAnswer: 'participate',
        explanation: 'Cụm từ cố định: "participate in" = tham gia vào. ("attend" không đi với "in", "join" đi trực tiếp với tân ngữ).',
        hint: 'Đi kèm với giới từ "in".',
      },
      {
        id: 'q-mc-5',
        questionOrder: 5,
        questionText: 'Neither the teacher nor the students ______ satisfied with the noisy test environment.',
        type: 'multiple_choice',
        options: ['were', 'was', 'is', 'are'],
        correctAnswer: 'were',
        explanation: 'Quy tắc phù hợp chủ ngữ: Với "Neither... nor...", động từ chia theo chủ ngữ gần nhất (the students - số nhiều) trong thì quá khứ -> chọn "were".',
        hint: 'Động từ chia theo danh từ đứng sau "nor" (the students).',
      },
      {
        id: 'q-mc-6',
        questionOrder: 6,
        questionText: 'She decided to ______ an online course in computer programming during the summer break.',
        type: 'multiple_choice',
        options: ['enroll in', 'take over', 'make up', 'drop out'],
        correctAnswer: 'enroll in',
        explanation: 'Cụm động từ: "enroll in a course" nghĩa là đăng ký ghi danh tham gia một khóa học.',
        hint: 'Đăng ký tham gia một lớp học.',
      },
      {
        id: 'q-mc-7',
        questionOrder: 7,
        questionText: 'If you want to achieve a high score in English exams, you must ______ practicing regularly.',
        type: 'multiple_choice',
        options: ['keep on', 'give up', 'put off', 'break down'],
        correctAnswer: 'keep on',
        explanation: '"keep on + V-ing" nghĩa là kiên trì tiếp tục làm việc gì đó.',
        hint: 'Đồng nghĩa với "continue".',
      },
      {
        id: 'q-mc-8',
        questionOrder: 8,
        questionText: 'The principal delivered an ______ speech that motivated all freshmen at the opening ceremony.',
        type: 'multiple_choice',
        options: ['inspiring', 'inspired', 'inspiration', 'inspire'],
        correctAnswer: 'inspiring',
        explanation: 'Cần một tính từ chỉ tính chất của bài phát biểu ("an inspiring speech" = bài phát biểu truyền cảm hứng).',
        hint: 'Tính từ mang nghĩa chủ động truyền cảm hứng cho người nghe.',
      },
    ],
  },

  // 2. True / False
  {
    id: 'ex-tf-1',
    title: 'Healthy Habits & Nutrition',
    topicId: 'health',
    topicTitle: 'Health',
    level: 'Beginner',
    type: 'true_false',
    passage: `Drinking enough water every day is essential for good health. Doctors recommend at least 1.5 to 2 liters of water daily. Staying hydrated improves concentration and skin health. On the other hand, consuming too many sugary sodas can cause fatigue and dental issues. Furthermore, engaging in 30 minutes of moderate aerobic exercise daily strengthens cardiovascular fitness and reduces anxiety. A balanced diet incorporating fresh greens and lean proteins provides sustained energy throughout demanding school days.`,
    questions: [
      {
        id: 'q-tf-1',
        questionOrder: 1,
        questionText: 'Drinking 1.5 to 2 liters of water daily is recommended by doctors.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Trong bài có câu: "Doctors recommend at least 1.5 to 2 liters of water daily."',
      },
      {
        id: 'q-tf-2',
        questionOrder: 2,
        questionText: 'Drinking plenty of water makes people feel tired and lose concentration.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Bài viết khẳng định uống đủ nước "improves concentration", còn đồ uống ngọt có ga mới gây ra "fatigue".',
      },
      {
        id: 'q-tf-3',
        questionOrder: 3,
        questionText: 'Sugary drinks can have negative effects on teeth.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Bài viết nêu rõ: "consuming too many sugary sodas can cause fatigue and dental issues".',
      },
      {
        id: 'q-tf-4',
        questionOrder: 4,
        questionText: 'Engaging in 30 minutes of daily aerobic exercise strengthens cardiovascular health.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Bài viết nêu rõ: "engaging in 30 minutes of moderate aerobic exercise daily strengthens cardiovascular fitness..."',
      },
      {
        id: 'q-tf-5',
        questionOrder: 5,
        questionText: 'A balanced diet should avoid all fresh greens and lean proteins completely.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Bài viết khuyên nên bổ sung rau xanh và đạm nạc: "A balanced diet incorporating fresh greens and lean proteins provides sustained energy..."',
      },
      {
        id: 'q-tf-6',
        questionOrder: 6,
        questionText: 'Regular physical activity can help students reduce levels of anxiety.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Đoạn văn khẳng định tập thể dục vừa phải giúp "reduces anxiety".',
      },
    ],
  },

  // 3. Fill in the Blank (Cloze)
  {
    id: 'ex-fitb-1',
    title: 'Daily Morning Routine Cloze',
    topicId: 'introduce-yourself',
    topicTitle: 'Introduce yourself',
    level: 'Beginner',
    type: 'fill_in_the_blank',
    passage: 'Every morning, I wake up at 6:00 AM. I brush my teeth and ______ a healthy breakfast with my family. Then, I ride my bicycle to school. In the afternoon, I ______ my friends in the park to play badminton. In the evening, I ______ my homework before dinner. Finally, I usually ______ for half an hour to relax before going to sleep.',
    questions: [
      {
        id: 'q-fitb-1',
        questionOrder: 1,
        questionText: 'Every morning, I wake up at 6:00 AM. I brush my teeth and ______ a healthy breakfast.',
        type: 'fill_in_the_blank',
        correctAnswer: 'have',
        wordBank: ['have', 'eat', 'cook', 'make', 'meet', 'play'],
        explanation: 'Cụm từ "have breakfast" hoặc "eat breakfast" đều chuẩn xác, phổ biến nhất là "have".',
        hint: 'Động từ thường đi với "breakfast".',
      },
      {
        id: 'q-fitb-2',
        questionOrder: 2,
        questionText: 'In the afternoon, I ______ my friends in the park to play badminton.',
        type: 'fill_in_the_blank',
        correctAnswer: 'meet',
        wordBank: ['meet', 'see', 'catch', 'talk'],
        explanation: '"meet my friends" nghĩa là gặp gỡ bạn bè.',
        hint: 'Gặp gỡ bạn bè sau giờ học.',
      },
      {
        id: 'q-fitb-3',
        questionOrder: 3,
        questionText: 'In the evening, I usually ______ all my homework before dinner.',
        type: 'fill_in_the_blank',
        correctAnswer: 'complete',
        wordBank: ['complete', 'finish', 'do', 'make', 'write'],
        explanation: '"complete my homework" = hoàn thành bài tập về nhà.',
        hint: 'Bắt đầu bằng chữ c.',
      },
      {
        id: 'q-fitb-4',
        questionOrder: 4,
        questionText: 'Finally, I usually ______ for half an hour to relax before sleeping.',
        type: 'fill_in_the_blank',
        correctAnswer: 'read',
        wordBank: ['read', 'study', 'sleep', 'look'],
        explanation: '"read for half an hour" = đọc sách nửa tiếng để thư giãn.',
        hint: 'Đọc sách truyện trước khi ngủ.',
      },
      {
        id: 'q-fitb-5',
        questionOrder: 5,
        questionText: 'On weekends, I love to ______ my grandparents in the countryside.',
        type: 'fill_in_the_blank',
        correctAnswer: 'visit',
        wordBank: ['visit', 'call', 'invite', 'see'],
        explanation: '"visit my grandparents" = về thăm ông bà.',
        hint: 'Động từ đi thăm người thân.',
      },
      {
        id: 'q-fitb-6',
        questionOrder: 6,
        questionText: 'During my visits, I always ______ my grandfather with gardening.',
        type: 'fill_in_the_blank',
        correctAnswer: 'help',
        wordBank: ['help', 'make', 'do', 'give'],
        explanation: 'Cấu trúc "help someone with something" = giúp đỡ ai việc gì.',
        hint: 'Giúp đỡ ông làm vườn.',
      },
    ],
  },

  // 4. Matching Pairs (Vocabulary & Definition)
  {
    id: 'ex-match-1',
    title: 'Travel & Airport Vocabulary Matching',
    topicId: 'at-airport',
    topicTitle: 'At the airport',
    level: 'Intermediate',
    type: 'matching',
    questions: [
      {
        id: 'q-match-1',
        questionOrder: 1,
        questionText: 'Match each airport term on the left with its correct meaning on the right.',
        type: 'matching',
        correctAnswer: 'Boarding pass:Ticket allowing passenger onto airplane;Baggage claim:Area where travelers pick up luggage;Departure lounge:Waiting area before flight boarding;Customs:Checkpoint inspecting goods entering country',
        matchingPairs: [
          { left: 'Boarding pass', right: 'Ticket allowing passenger onto airplane' },
          { left: 'Baggage claim', right: 'Area where travelers pick up luggage' },
          { left: 'Departure lounge', right: 'Waiting area before flight boarding' },
          { left: 'Customs', right: 'Checkpoint inspecting goods entering country' },
        ],
        explanation: 'Boarding pass (thẻ lên máy bay), Baggage claim (nơi lấy hành lý), Departure lounge (phòng chờ bay), Customs (hải quan).',
      },
      {
        id: 'q-match-2',
        questionOrder: 2,
        questionText: 'Match each hotel and hospitality term with its accurate definition.',
        type: 'matching',
        correctAnswer: 'Single room:Room designed for one occupant;Check-in:Registering arrival at hotel reception;Concierge:Hotel staff assisting with tours and bookings;Complimentary:Service provided free of charge',
        matchingPairs: [
          { left: 'Single room', right: 'Room designed for one occupant' },
          { left: 'Check-in', right: 'Registering arrival at hotel reception' },
          { left: 'Concierge', right: 'Hotel staff assisting with tours and bookings' },
          { left: 'Complimentary', right: 'Service provided free of charge' },
        ],
        explanation: 'Single room (phòng đơn), Check-in (thủ tục nhận phòng), Concierge (nhân viên hướng dẫn/hỗ trợ), Complimentary (miễn phí kèm theo).',
      },
      {
        id: 'q-match-3',
        questionOrder: 3,
        questionText: 'Match each dining and restaurant term with its definition.',
        type: 'matching',
        correctAnswer: 'Appetizer:Small starter dish before the main course;Beverage:Any drink other than plain water;Bill / Check:Printed summary of costs for the meal;Dessert:Sweet course served at the end of meal',
        matchingPairs: [
          { left: 'Appetizer', right: 'Small starter dish before the main course' },
          { left: 'Beverage', right: 'Any drink other than plain water' },
          { left: 'Bill / Check', right: 'Printed summary of costs for the meal' },
          { left: 'Dessert', right: 'Sweet course served at the end of meal' },
        ],
        explanation: 'Appetizer (món khai vị), Beverage (đồ uống), Bill/Check (hóa đơn thanh toán), Dessert (món tráng miệng).',
      },
      {
        id: 'q-match-4',
        questionOrder: 4,
        questionText: 'Match each green technology term with its environmental role.',
        type: 'matching',
        correctAnswer: 'Solar panels:Convert sunlight directly into electricity;Wind turbines:Harness kinetic wind to generate power;Composting:Recycle food scraps into fertile soil;Electric cars:Vehicles operating without gasoline emissions',
        matchingPairs: [
          { left: 'Solar panels', right: 'Convert sunlight directly into electricity' },
          { left: 'Wind turbines', right: 'Harness kinetic wind to generate power' },
          { left: 'Composting', right: 'Recycle food scraps into fertile soil' },
          { left: 'Electric cars', right: 'Vehicles operating without gasoline emissions' },
        ],
        explanation: 'Solar panels (pin mặt trời), Wind turbines (tua-bin gió), Composting (ủ phân hữu cơ), Electric cars (xe điện).',
      },
    ],
  },

  // 5. Sentence Reordering (Sắp xếp câu)
  {
    id: 'ex-reorder-1',
    title: 'Sentence Scramble: Ordering Food & Daily English',
    topicId: 'restaurant',
    topicTitle: 'Restaurant',
    level: 'Intermediate',
    type: 'sentence_reorder',
    questions: [
      {
        id: 'q-reorder-1',
        questionOrder: 1,
        questionText: 'Arrange the scrambled words into a correct, polite English sentence.',
        type: 'sentence_reorder',
        scrambledWords: ['Could', 'have', 'the', 'please', 'check', 'we', '?'],
        correctAnswer: 'Could we have the check please ?',
        explanation: 'Cấu trúc câu hỏi lịch sự: Could + S + V + O + please? ("Could we have the check, please?")',
        hint: 'Bắt đầu bằng từ trợ động từ lịch sự "Could".',
      },
      {
        id: 'q-reorder-2',
        questionOrder: 2,
        questionText: 'Arrange the scrambled words into a complete restaurant recommendation sentence.',
        type: 'sentence_reorder',
        scrambledWords: ['specialty', 'seafood', 'is', 'This', 'soup', 'the', 'house', '.'],
        correctAnswer: 'This seafood soup is the house specialty .',
        explanation: 'Trật tự câu: S (This seafood soup) + V (is) + C (the house specialty).',
        hint: 'Chủ ngữ là món súp hải sản.',
      },
      {
        id: 'q-reorder-3',
        questionOrder: 3,
        questionText: 'Arrange the scrambled words to ask for directions politely.',
        type: 'sentence_reorder',
        scrambledWords: ['Could', 'tell', 'way', 'the', 'you', 'me', 'to', 'museum', 'the', '?'],
        correctAnswer: 'Could you tell me the way to the museum ?',
        explanation: 'Cấu trúc hỏi đường: Could you tell me the way to + địa điểm?',
        hint: 'Bắt đầu bằng "Could you tell me...".',
      },
      {
        id: 'q-reorder-4',
        questionOrder: 4,
        questionText: 'Arrange the scrambled words to express an upcoming vacation plan.',
        type: 'sentence_reorder',
        scrambledWords: ['am', 'I', 'planning', 'to', 'travel', 'Da Nang', 'to', 'summer', 'this', '.'],
        correctAnswer: 'I am planning to travel to Da Nang this summer .',
        explanation: 'Cấu trúc thì hiện tại tiếp diễn diễn tả kế hoạch: S + am/is/are + planning to + V.',
        hint: 'Chủ ngữ là "I".',
      },
      {
        id: 'q-reorder-5',
        questionOrder: 5,
        questionText: 'Arrange the scrambled words to give good health advice.',
        type: 'sentence_reorder',
        scrambledWords: ['should', 'You', 'drink', 'water', 'every', 'more', 'day', '.'],
        correctAnswer: 'You should drink more water every day .',
        explanation: 'Cấu trúc khuyên bảo: S (You) + should + V (drink) + O (more water) + trạng từ (every day).',
        hint: 'Bắt đầu bằng đại từ "You".',
      },
      {
        id: 'q-reorder-6',
        questionOrder: 6,
        questionText: 'Arrange the scrambled words into a polite offer of assistance.',
        type: 'sentence_reorder',
        scrambledWords: ['May', 'help', 'you', 'with', 'I', 'heavy', 'that', 'suitcase', '?'],
        correctAnswer: 'May I help you with that heavy suitcase ?',
        explanation: 'Đề nghị giúp đỡ lịch sự: May I help you with + danh từ?',
        hint: 'Bắt đầu bằng từ đề nghị lịch sự "May I".',
      },
    ],
  },

  // 6. Vocabulary in Context
  {
    id: 'ex-vocab-1',
    title: 'Environment & Climate Change Words',
    topicId: 'environment',
    topicTitle: 'Environment',
    level: 'Advanced',
    type: 'vocabulary',
    questions: [
      {
        id: 'q-vocab-1',
        questionOrder: 1,
        questionText: 'What is the closest synonym to the word "sustainable" in environmental protection?',
        type: 'vocabulary',
        options: ['Renewable & long-lasting', 'Temporary & fast', 'Expensive & rare', 'Destructive & harmful'],
        correctAnswer: 'Renewable & long-lasting',
        explanation: '"Sustainable" (bền vững) đồng nghĩa với "renewable & long-lasting" (có thể tái tạo và duy trì lâu dài).',
        hint: 'Năng lượng mặt trời là một ví dụ về nguồn năng lượng này.',
      },
      {
        id: 'q-vocab-2',
        questionOrder: 2,
        questionText: 'The process of turning waste materials into reusable items is called ______.',
        type: 'vocabulary',
        options: ['recycling', 'deforestation', 'emission', 'biodiversity'],
        correctAnswer: 'recycling',
        explanation: '"Recycling" là quá trình tái chế rác thải.',
        hint: 'Biểu tượng hình 3 mũi tên xoay vòng.',
      },
      {
        id: 'q-vocab-3',
        questionOrder: 3,
        questionText: 'What does the term "biodegradable" mean when describing modern packaging materials?',
        type: 'vocabulary',
        options: [
          'Capable of being decomposed naturally by bacteria',
          'Immune to all water and sunlight',
          'Manufactured entirely from toxic chemicals',
          'Dangerous and non-recyclable'
        ],
        correctAnswer: 'Capable of being decomposed naturally by bacteria',
        explanation: '"Biodegradable" (phân hủy sinh học) là khả năng phân hủy tự nhiên an toàn trong môi trường bởi vi sinh vật.',
        hint: 'Có tiền tố "bio-" (sinh học) và "degrade" (phân hủy).',
      },
      {
        id: 'q-vocab-4',
        questionOrder: 4,
        questionText: 'The total amount of greenhouse gases produced by human activities is called our ______.',
        type: 'vocabulary',
        options: ['carbon footprint', 'solar capacity', 'water cycle', 'geological layer'],
        correctAnswer: 'carbon footprint',
        explanation: '"Carbon footprint" (dấu chân carbon) là lượng khí thải nhà kính do cá nhân hoặc tổ chức tạo ra.',
        hint: 'Từ ghép chứa từ chỉ carbon và "dấu chân".',
      },
      {
        id: 'q-vocab-5',
        questionOrder: 5,
        questionText: 'Energy sources such as wind, solar, and hydroelectric are classified as ______ energy.',
        type: 'vocabulary',
        options: ['renewable', 'fossil', 'depletable', 'combustible'],
        correctAnswer: 'renewable',
        explanation: '"Renewable energy" là năng lượng tái tạo không bao giờ cạn kiệt.',
        hint: 'Bắt đầu bằng tiền tố re- (làm mới lại).',
      },
      {
        id: 'q-vocab-6',
        questionOrder: 6,
        questionText: 'A biological community of interacting organisms and their physical environment is an ______.',
        type: 'vocabulary',
        options: ['ecosystem', 'atmosphere', 'ozone layer', 'aquarium'],
        correctAnswer: 'ecosystem',
        explanation: '"Ecosystem" là hệ sinh thái nơi các sinh vật tương tác hài hòa với môi trường sống.',
        hint: 'Hệ thống sinh thái tự nhiên.',
      },
    ],
  },

  // 7. Grammar (Conditional & Modals)
  {
    id: 'ex-grammar-1',
    title: 'Conditional Sentences & Modal Verbs',
    topicId: 'future-plans',
    topicTitle: 'Future plans',
    level: 'Intermediate',
    type: 'grammar',
    questions: [
      {
        id: 'q-gram-1',
        questionOrder: 1,
        questionText: 'If I pass the English exam with a high score, my parents ______ me a new laptop.',
        type: 'grammar',
        options: ['will buy', 'would buy', 'bought', 'have bought'],
        correctAnswer: 'will buy',
        explanation: 'Câu điều kiện loại 1 diễn tả sự việc có thể xảy ra ở hiện tại hoặc tương lai: If + S + V(hiện tại đơn), S + will + V.',
        hint: 'Mệnh đề If chia ở hiện tại ("pass").',
      },
      {
        id: 'q-gram-2',
        questionOrder: 2,
        questionText: 'If I ______ more spare time, I would volunteer at the local animal shelter.',
        type: 'grammar',
        options: ['had', 'have', 'will have', 'am having'],
        correctAnswer: 'had',
        explanation: 'Câu điều kiện loại 2 giả định điều trái ngược với hiện tại: If + S + V2/ed, S + would + V.',
        hint: 'Mệnh đề chính dùng "would volunteer".',
      },
      {
        id: 'q-gram-3',
        questionOrder: 3,
        questionText: 'If it ______ heavily tomorrow morning, our class will cancel the outdoor sports festival.',
        type: 'grammar',
        options: ['rains', 'will rain', 'rained', 'is raining'],
        correctAnswer: 'rains',
        explanation: 'Trong mệnh đề điều kiện loại 1 (mệnh đề If), luôn dùng thì hiện tại đơn (rains), không dùng "will rain".',
        hint: 'Mệnh đề If không đi với "will".',
      },
      {
        id: 'q-gram-4',
        questionOrder: 4,
        questionText: 'Unless you ______ your alarm clock tonight, you will be late for the school excursion.',
        type: 'grammar',
        options: ['set', 'don\'t set', 'will set', 'are setting'],
        correctAnswer: 'set',
        explanation: '"Unless" = "If not". Bản thân "Unless" đã mang nghĩa phủ định nên động từ phía sau ở dạng khẳng định: "Unless you set...".',
        hint: 'Không dùng phủ định "don\'t" sau "Unless".',
      },
      {
        id: 'q-gram-5',
        questionOrder: 5,
        questionText: 'I wish I ______ speak fluent Spanish so I could communicate with the exchange students.',
        type: 'grammar',
        options: ['could', 'can', 'will', 'may'],
        correctAnswer: 'could',
        explanation: 'Cấu trúc câu ước ở hiện tại: S + wish + S + V2/ed hoặc could + V (could speak).',
        hint: 'Lùi thì của "can" về quá khứ.',
      },
      {
        id: 'q-gram-6',
        questionOrder: 6,
        questionText: 'All students ______ wear their school uniforms on Mondays and during formal assemblies.',
        type: 'grammar',
        options: ['must', 'might', 'could', 'would'],
        correctAnswer: 'must',
        explanation: 'Động từ khuyết thiếu "must" diễn tả quy định bắt buộc của nhà trường.',
        hint: 'Diễn tả quy định nội quy bắt buộc.',
      },
    ],
  },

  // 8. Reading Comprehension (Đọc hiểu)
  {
    id: 'ex-reading-1',
    title: 'The Rise of Artificial Intelligence in Education',
    topicId: 'technology',
    topicTitle: 'Technology',
    level: 'Advanced',
    type: 'reading',
    passage: `Artificial Intelligence (AI) is transforming modern education at an unprecedented pace. In language learning, AI tools can act as round-the-clock conversational partners, providing immediate pronunciation feedback and tailored grammar corrections. 

Unlike traditional classroom settings where a teacher must divide attention among dozens of students, AI systems adapt to individual learning speeds. For example, a student struggling with past tenses can receive targeted exercises, while an advanced learner can engage in complex debates on global issues. 

However, educators emphasize that AI should complement rather than replace human teachers. Empathy, emotional encouragement, and collaborative human interaction remain irreplaceable components of holistic growth.`,
    questions: [
      {
        id: 'q-read-1',
        questionOrder: 1,
        questionText: 'According to the passage, what is a primary advantage of AI in language learning?',
        type: 'multiple_choice',
        options: [
          'Immediate feedback and personalized pacing',
          'Eliminating the need for human teachers completely',
          'Decreasing student motivation',
          'Making all exercises identical for all students'
        ],
        correctAnswer: 'Immediate feedback and personalized pacing',
        explanation: 'Đoạn văn nêu rõ AI cung cấp phản hồi tức thì ("immediate feedback") và thích ứng với tốc độ học của từng cá nhân ("adapt to individual learning speeds").',
        evidenceQuote: 'providing immediate pronunciation feedback and tailored grammar corrections',
      },
      {
        id: 'q-read-2',
        questionOrder: 2,
        questionText: 'According to educators, should AI completely replace human teachers?',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Đoạn cuối nhấn mạnh: "educators emphasize that AI should complement rather than replace human teachers."',
        evidenceQuote: 'educators emphasize that AI should complement rather than replace human teachers',
      },
      {
        id: 'q-read-3',
        questionOrder: 3,
        questionText: 'What does the word "unprecedented" in the first paragraph mean?',
        type: 'multiple_choice',
        options: ['Never seen before or greater than ever', 'Very slow and gradual', 'Outdated and useless', 'Difficult to understand'],
        correctAnswer: 'Never seen before or greater than ever',
        explanation: '"Unprecedented" nghĩa là chưa từng có tiền lệ, vượt bậc hơn bao giờ hết.',
        evidenceQuote: 'transforming modern education at an unprecedented pace',
      },
      {
        id: 'q-read-4',
        questionOrder: 4,
        questionText: 'Why does traditional classroom teaching differ from an AI-driven learning system?',
        type: 'multiple_choice',
        options: [
          'Teachers have to divide their attention among many students at once',
          'Traditional classrooms only teach advanced learners',
          'AI systems require a classroom full of students to function',
          'Traditional teachers do not give any feedback'
        ],
        correctAnswer: 'Teachers have to divide their attention among many students at once',
        explanation: 'Đoạn 2 nêu rõ: "Unlike traditional classroom settings where a teacher must divide attention among dozens of students, AI systems adapt to individual learning speeds."',
        evidenceQuote: 'teacher must divide attention among dozens of students',
      },
      {
        id: 'q-read-5',
        questionOrder: 5,
        questionText: 'True or False: An advanced learner using an AI system would be restricted to basic past tense drills.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Đoạn 2 nêu rõ: "...while an advanced learner can engage in complex debates on global issues."',
        evidenceQuote: 'advanced learner can engage in complex debates on global issues',
      },
      {
        id: 'q-read-6',
        questionOrder: 6,
        questionText: 'In paragraph 3, the word "irreplaceable" is closest in meaning to:',
        type: 'multiple_choice',
        options: [
          'Essential and impossible to substitute',
          'Easy to reproduce',
          'Temporary and fleeting',
          'Costly and unnecessary'
        ],
        correctAnswer: 'Essential and impossible to substitute',
        explanation: '"Irreplaceable" nghĩa là không thể thay thế được, tối quan trọng đối với sự phát triển toàn diện.',
        evidenceQuote: 'irreplaceable components of holistic growth',
      },
      {
        id: 'q-read-7',
        questionOrder: 7,
        questionText: 'Which essential human qualities are mentioned that AI cannot provide?',
        type: 'multiple_choice',
        options: [
          'Empathy, emotional encouragement, and collaborative human interaction',
          'Fast grammar checking and instant scoring',
          'Pronunciation testing and automated vocabulary flashcards',
          '24/7 round-the-clock availability'
        ],
        correctAnswer: 'Empathy, emotional encouragement, and collaborative human interaction',
        explanation: 'Đoạn 3 chỉ rõ: "Empathy, emotional encouragement, and collaborative human interaction remain irreplaceable components of holistic growth."',
        evidenceQuote: 'Empathy, emotional encouragement, and collaborative human interaction',
      },
      {
        id: 'q-read-8',
        questionOrder: 8,
        questionText: 'What is the main conclusion of the passage regarding AI in modern education?',
        type: 'multiple_choice',
        options: [
          'AI is a valuable complementary tool, but human teachers remain indispensable',
          'Schools should stop using AI to protect traditional methods',
          'AI will fully take over schools within the next few years',
          'Language learning is too difficult to be aided by software'
        ],
        correctAnswer: 'AI is a valuable complementary tool, but human teachers remain indispensable',
        explanation: 'Tác giả kết luận AI là công cụ hỗ trợ tuyệt vời ("complement rather than replace"), kết hợp cùng sự đồng cảm và gắn kết của giáo viên con người.',
        evidenceQuote: 'AI should complement rather than replace human teachers',
      },
    ],
  },

  {
    id: 'ex-reading-2',
    title: 'The Hidden Power of Daily Reading Habits',
    topicId: 'education',
    topicTitle: 'Education',
    level: 'Intermediate',
    type: 'reading',
    passage: `Cultivating a daily reading habit is widely recognized as one of the most effective ways to boost cognitive performance and linguistic competence. When people read fiction or non-fiction for even twenty minutes every evening, brain connectivity significantly strengthens, especially in the left temporal cortex, which is associated with language receptivity.

Beyond neurological benefits, reading extensively expands active and passive vocabulary. Readers encounter rare words in natural contexts, making comprehension and retention far more organic than memorizing static word lists. Furthermore, immersing oneself in characters' perspectives nurtures deep emotional empathy and cross-cultural understanding.

In our screen-dominated world where short videos fragment our attention spans, sustained deep reading acts as a protective shield for concentration. Experts suggest scheduling reading time like any important appointment, transforming reading from a chore into a lifelong sanctuary of discovery.`,
    questions: [
      {
        id: 'q-read2-1',
        questionOrder: 1,
        questionText: 'What is the central focus of the reading passage?',
        type: 'multiple_choice',
        options: [
          'The profound cognitive, linguistic, and mental benefits of daily reading',
          'Why paper books are completely obsolete compared to e-books',
          'How short videos help students learn languages faster',
          'The best bookstores in the world to visit'
        ],
        correctAnswer: 'The profound cognitive, linguistic, and mental benefits of daily reading',
        explanation: 'Bài đọc nêu bật các lợi ích toàn diện của việc đọc sách mỗi ngày đối với não bộ, ngôn ngữ và khả năng tập trung.',
        evidenceQuote: 'Cultivating a daily reading habit is widely recognized as one of the most effective ways to boost cognitive performance and linguistic competence',
      },
      {
        id: 'q-read2-2',
        questionOrder: 2,
        questionText: 'Which area of the brain is mentioned as being strengthened through regular reading?',
        type: 'multiple_choice',
        options: [
          'The left temporal cortex',
          'The visual processing center only',
          'The motor reflexes cortex',
          'The auditory nerve pathway'
        ],
        correctAnswer: 'The left temporal cortex',
        explanation: 'Đoạn 1 nêu: "...especially in the left temporal cortex, which is associated with language receptivity."',
        evidenceQuote: 'especially in the left temporal cortex, which is associated with language receptivity',
      },
      {
        id: 'q-read2-3',
        questionOrder: 3,
        questionText: 'True or False: Memorizing static word lists is more natural and organic than reading words in context.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Đoạn 2 nêu rõ đọc từ trong ngữ cảnh tự nhiên ("in natural contexts") hiệu quả và tự nhiên hơn nhiều so với ghi nhớ danh sách từ tĩnh ("far more organic than memorizing static word lists").',
        evidenceQuote: 'making comprehension and retention far more organic than memorizing static word lists',
      },
      {
        id: 'q-read2-4',
        questionOrder: 4,
        questionText: 'In paragraph 2, what emotional benefit is gained from immersing oneself in characters\' perspectives?',
        type: 'multiple_choice',
        options: [
          'Nurturing deep emotional empathy and cross-cultural understanding',
          'Becoming detached from real-world relationships',
          'Increasing competitive aggression',
          'Avoiding social communication'
        ],
        correctAnswer: 'Nurturing deep emotional empathy and cross-cultural understanding',
        explanation: 'Đoạn 2: "...nurtures deep emotional empathy and cross-cultural understanding."',
        evidenceQuote: 'immersing oneself in characters\' perspectives nurtures deep emotional empathy and cross-cultural understanding',
      },
      {
        id: 'q-read2-5',
        questionOrder: 5,
        questionText: 'What does the word "fragment" in the third paragraph most likely mean?',
        type: 'multiple_choice',
        options: [
          'Break into small, disjointed pieces',
          'Strengthen and expand',
          'Organize in chronological order',
          'Double the speed of'
        ],
        correctAnswer: 'Break into small, disjointed pieces',
        explanation: '"Fragment" ở đây có nghĩa là chia cắt, làm phân mảnh khả năng tập trung chú ý.',
        evidenceQuote: 'short videos fragment our attention spans',
      },
      {
        id: 'q-read2-6',
        questionOrder: 6,
        questionText: 'True or False: According to experts, reading should be scheduled like an important appointment.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Đoạn cuối: "Experts suggest scheduling reading time like any important appointment..."',
        evidenceQuote: 'Experts suggest scheduling reading time like any important appointment',
      },
      {
        id: 'q-read2-7',
        questionOrder: 7,
        questionText: 'Why does sustained deep reading act as a "protective shield"?',
        type: 'multiple_choice',
        options: [
          'It protects concentration from being eroded by fragmented digital distractions',
          'It shields eyes from screen radiation',
          'It replaces the need for sleep',
          'It prevents readers from using smartphones completely'
        ],
        correctAnswer: 'It protects concentration from being eroded by fragmented digital distractions',
        explanation: 'Đọc sâu giúp bảo vệ khả năng tập trung trước thói quen lướt nội dung ngắn làm đứt đoạn chú ý.',
        evidenceQuote: 'sustained deep reading acts as a protective shield for concentration',
      },
    ],
  },

  {
    id: 'ex-reading-3',
    title: 'Safeguarding Coral Reefs from Ocean Warming',
    topicId: 'environment',
    topicTitle: 'Environment',
    level: 'Advanced',
    type: 'reading',
    passage: `Coral reefs are frequently referred to as the rainforests of the sea, harboring approximately twenty-five percent of all marine species despite occupying less than one percent of the ocean floor. These vibrant underwater ecosystems offer indispensable services, ranging from coastal erosion protection to supporting global fisheries and eco-tourism livelihoods.

However, escalating greenhouse gas emissions have precipitated widespread coral bleaching events. When seawater temperatures exceed typical seasonal thresholds, corals expel the symbiotic algae living within their tissues, losing both their vivid pigmentation and principal food source. Without prompt ocean cooling, extended bleaching leads to catastrophic mortality across entire barrier formations.

In response, international marine scientists are collaborating on groundbreaking restoration initiatives. Marine laboratories are breeding heat-resilient coral micro-fragments and utilizing 3D-printed ceramic structures to accelerate reef regeneration. Nevertheless, environmentalists caution that technological intervention must be paired with aggressive global emission reductions to secure the permanent survival of marine biodiversity.`,
    questions: [
      {
        id: 'q-read3-1',
        questionOrder: 1,
        questionText: 'Why are coral reefs often compared to rainforests?',
        type: 'multiple_choice',
        options: [
          'Because they house about a quarter of all marine species despite covering a tiny fraction of the ocean floor',
          'Because they have dense trees growing beneath the seawater surface',
          'Because they experience heavy rainfall throughout the year',
          'Because they are located exclusively near tropical rain forests on land'
        ],
        correctAnswer: 'Because they house about a quarter of all marine species despite covering a tiny fraction of the ocean floor',
        explanation: 'Đoạn 1 nêu rõ: "...harboring approximately twenty-five percent of all marine species despite occupying less than one percent of the ocean floor."',
        evidenceQuote: 'harboring approximately twenty-five percent of all marine species despite occupying less than one percent of the ocean floor',
      },
      {
        id: 'q-read3-2',
        questionOrder: 2,
        questionText: 'What is the immediate biological cause of coral bleaching mentioned in paragraph 2?',
        type: 'multiple_choice',
        options: [
          'Corals expel the symbiotic algae residing inside their tissues when water temperatures exceed normal thresholds',
          'Fish consume all the coral branches during high tides',
          'Sunlight is completely blocked by sea ice formations',
          'Marine plants overgrow and suffocate the coral polyps'
        ],
        correctAnswer: 'Corals expel the symbiotic algae residing inside their tissues when water temperatures exceed normal thresholds',
        explanation: 'Đoạn 2 giải thích: "When seawater temperatures exceed typical seasonal thresholds, corals expel the symbiotic algae living within their tissues..."',
        evidenceQuote: 'corals expel the symbiotic algae living within their tissues, losing both their vivid pigmentation and principal food source',
      },
      {
        id: 'q-read3-3',
        questionOrder: 3,
        questionText: 'True or False: Coral reefs provide natural coastal protection against erosion.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Đoạn 1 nêu rõ các rạn san hô cung cấp dịch vụ: "...ranging from coastal erosion protection to supporting global fisheries..."',
        evidenceQuote: 'ranging from coastal erosion protection to supporting global fisheries',
      },
      {
        id: 'q-read3-4',
        questionOrder: 4,
        questionText: 'What innovative technological restoration methods are researchers deploying?',
        type: 'multiple_choice',
        options: [
          'Breeding heat-resilient coral micro-fragments and installing 3D-printed ceramic structures',
          'Building giant glass domes over entire oceans',
          'Transporting all corals into indoor fresh-water aquariums permanently',
          'Freezing ocean surface waters with artificial icebergs'
        ],
        correctAnswer: 'Breeding heat-resilient coral micro-fragments and installing 3D-printed ceramic structures',
        explanation: 'Đoạn 3 chỉ rõ: "Marine laboratories are breeding heat-resilient coral micro-fragments and utilizing 3D-printed ceramic structures..."',
        evidenceQuote: 'breeding heat-resilient coral micro-fragments and utilizing 3D-printed ceramic structures',
      },
      {
        id: 'q-read3-5',
        questionOrder: 5,
        questionText: 'In paragraph 2, what does the word "precipitated" most closely mean?',
        type: 'multiple_choice',
        options: [
          'Triggered or caused to happen rapidly',
          'Prevented from occurring',
          'Slowed down over centuries',
          'Measured with precision instruments'
        ],
        correctAnswer: 'Triggered or caused to happen rapidly',
        explanation: '"Precipitated" trong ngữ cảnh này có nghĩa là thúc đẩy, châm ngòi hoặc gây ra nhanh chóng các hiện tượng tẩy trắng san hô.',
        evidenceQuote: 'escalating greenhouse gas emissions have precipitated widespread coral bleaching events',
      },
      {
        id: 'q-read3-6',
        questionOrder: 6,
        questionText: 'True or False: Technological restoration alone is sufficient to guarantee the survival of coral reefs.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Đoạn 3 khẳng định: "technological intervention must be paired with aggressive global emission reductions to secure the permanent survival of marine biodiversity."',
        evidenceQuote: 'technological intervention must be paired with aggressive global emission reductions',
      },
      {
        id: 'q-read3-7',
        questionOrder: 7,
        questionText: 'What is the overarching conclusion of the passage?',
        type: 'multiple_choice',
        options: [
          'Protecting reefs requires uniting scientific restoration innovations with global climate commitments',
          'Coral reefs are doomed and cannot be saved by any human efforts',
          'Overfishing is the sole reason for coral reef destruction',
          'Scientists should abandon marine research and focus solely on land ecosystems'
        ],
        correctAnswer: 'Protecting reefs requires uniting scientific restoration innovations with global climate commitments',
        explanation: 'Bài viết kết luận giải pháp cứu rỗi san hô cần kết hợp cả sáng kiến sinh học phục hồi lẫn cam kết giảm phát thải khí nhà kính toàn cầu.',
        evidenceQuote: 'technological intervention must be paired with aggressive global emission reductions to secure the permanent survival of marine biodiversity',
      },
    ],
  },

  {
    id: 'ex-reading-4',
    title: 'The Science of Sleep and Academic Success',
    topicId: 'health',
    topicTitle: 'Health & Science',
    level: 'Intermediate',
    type: 'reading',
    passage: `In contemporary student life, sacrificing sleep to cram for upcoming examinations has unfortunately evolved into a badge of dedication. However, cognitive neuroscientists emphasize that sleep deprivation is severely counterproductive, directly sabotaging academic retention and emotional stability.

During non-rapid eye movement (NREM) deep sleep, the brain's hippocampus replays memories accumulated throughout the day, systematically transferring them to the neocortex for long-term storage. Without sufficient deep sleep cycles, newly learned vocabulary, scientific principles, and mathematical theorems remain volatile and rapidly decay.

Furthermore, rapid eye movement (REM) sleep fosters creative problem-solving by weaving disparate concepts into unified cognitive frameworks. Students who consistently achieve seven to nine hours of quality sleep demonstrate sharper reaction times, lower anxiety levels, and superior exam performance compared to peers who pull all-nighters.`,
    questions: [
      {
        id: 'q-read4-1',
        questionOrder: 1,
        questionText: 'What common misconception among students does the opening paragraph highlight?',
        type: 'multiple_choice',
        options: [
          'Sacrificing sleep to study is considered a commendable badge of dedication',
          'Sleeping eight hours every night is harmful for brain cells',
          'Drinking tea helps memory retention more than sleep',
          'Taking naps during exams leads to instant failure'
        ],
        correctAnswer: 'Sacrificing sleep to study is considered a commendable badge of dedication',
        explanation: 'Đoạn 1 nêu: "...sacrificing sleep to cram for upcoming examinations has unfortunately evolved into a badge of dedication."',
        evidenceQuote: 'sacrificing sleep to cram for upcoming examinations has unfortunately evolved into a badge of dedication',
      },
      {
        id: 'q-read4-2',
        questionOrder: 2,
        questionText: 'What crucial cognitive function takes place during NREM deep sleep?',
        type: 'multiple_choice',
        options: [
          'Memories are transferred from the hippocampus to the neocortex for long-term storage',
          'The brain completely shuts down all metabolic and neurological activity',
          'Eye movements reach maximum velocity to process daytime sights',
          'Old memories are completely erased to make room for exams'
        ],
        correctAnswer: 'Memories are transferred from the hippocampus to the neocortex for long-term storage',
        explanation: 'Đoạn 2 nêu rõ: "...the hippocampus replays memories accumulated throughout the day, systematically transferring them to the neocortex for long-term storage."',
        evidenceQuote: 'hippocampus replays memories accumulated throughout the day, systematically transferring them to the neocortex for long-term storage',
      },
      {
        id: 'q-read4-3',
        questionOrder: 3,
        questionText: 'True or False: Without deep sleep, newly acquired information decays and is easily forgotten.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Đoạn 2: "Without sufficient deep sleep cycles, newly learned vocabulary, scientific principles, and mathematical theorems remain volatile and rapidly decay."',
        evidenceQuote: 'newly learned vocabulary, scientific principles, and mathematical theorems remain volatile and rapidly decay',
      },
      {
        id: 'q-read4-4',
        questionOrder: 4,
        questionText: 'In paragraph 3, how does REM sleep benefit learning specifically?',
        type: 'multiple_choice',
        options: [
          'By fostering creative problem-solving and connecting disparate concepts',
          'By physically increasing head and muscle size',
          'By preventing the brain from dreaming',
          'By eliminating the need for daily revision'
        ],
        correctAnswer: 'By fostering creative problem-solving and connecting disparate concepts',
        explanation: 'Đoạn 3 chỉ rõ: "...REM sleep fosters creative problem-solving by weaving disparate concepts into unified cognitive frameworks."',
        evidenceQuote: 'fosters creative problem-solving by weaving disparate concepts into unified cognitive frameworks',
      },
      {
        id: 'q-read4-5',
        questionOrder: 5,
        questionText: 'What does the word "volatile" in paragraph 2 most nearly mean?',
        type: 'multiple_choice',
        options: [
          'Unstable and easily lost',
          'Permanent and unbreakable',
          'Extremely valuable and expensive',
          'Thoroughly organized'
        ],
        correctAnswer: 'Unstable and easily lost',
        explanation: '"Volatile" ở đây mang nghĩa không bền vững, dễ phai mờ và biến mất nếu không được củng cố trong giấc ngủ sâu.',
        evidenceQuote: 'remain volatile and rapidly decay',
      },
      {
        id: 'q-read4-6',
        questionOrder: 6,
        questionText: 'How many hours of sleep do researchers recommend for optimal academic performance?',
        type: 'multiple_choice',
        options: ['7 to 9 hours', '3 to 4 hours', '10 to 12 hours', 'Less than 5 hours'],
        correctAnswer: '7 to 9 hours',
        explanation: 'Đoạn 3 khẳng định: "Students who consistently achieve seven to nine hours of quality sleep demonstrate sharper reaction times..."',
        evidenceQuote: 'consistently achieve seven to nine hours of quality sleep',
      },
      {
        id: 'q-read4-7',
        questionOrder: 7,
        questionText: 'True or False: Pulling an all-nighter before an exam produces better test results than getting restful sleep.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Bài viết khẳng định ngủ đủ giấc mang lại điểm thi cao hơn và ít lo âu hơn so với việc thức trắng đêm (pull all-nighters).',
        evidenceQuote: 'superior exam performance compared to peers who pull all-nighters',
      },
    ],
  },

  {
    id: 'ex-reading-5',
    title: 'Preserving Cultural Heritage in Modern Vietnam',
    topicId: 'culture',
    topicTitle: 'Culture & Society',
    level: 'Intermediate',
    type: 'reading',
    passage: `Across Vietnam, ancient architectural landmarks, traditional handicraft villages, and intangible folk arts stand as living testaments to centuries of national resilience and creative ingenuity. From the water puppetry theatres of the Red River Delta to the UNESCO-recognized ancient town of Hoi An, cultural heritage connects modern citizens to ancestral virtues.

In an era of rapid urbanization, however, traditional craft villages face substantial hurdles. Many younger generations migrate toward metropolitan centers pursuing corporate careers, leaving traditional ceramic kilns, silk weaving looms, and lacquerware studios in danger of obsolescence.

Encouragingly, a vibrant wave of youthful artisans and cultural tech innovators is revitalizing Vietnamese heritage. By combining authentic artisan techniques with modern digital marketing and eco-conscious design, these pioneers are introducing Vietnamese folklore to global audiences while generating sustainable community income.`,
    questions: [
      {
        id: 'q-read5-1',
        questionOrder: 1,
        questionText: 'What is the main topic of the passage?',
        type: 'multiple_choice',
        options: [
          'The significance, current challenges, and modern revitalization of Vietnamese cultural heritage',
          'The complete modernization and replacement of traditional architecture',
          'Why young people should only work in traditional handicrafts',
          'A historical biography of ancient Vietnamese emperors'
        ],
        correctAnswer: 'The significance, current challenges, and modern revitalization of Vietnamese cultural heritage',
        explanation: 'Bài viết thảo luận toàn diện về giá trị của di sản văn hóa Việt Nam, những thách thức trong thời kỳ đô thị hóa và làn sóng phục hồi sáng tạo.',
        evidenceQuote: 'cultural heritage connects modern citizens to ancestral virtues',
      },
      {
        id: 'q-read5-2',
        questionOrder: 2,
        questionText: 'Which two famous cultural symbols are explicitly mentioned in the first paragraph?',
        type: 'multiple_choice',
        options: [
          'Water puppetry in the Red River Delta and the ancient town of Hoi An',
          'Floating markets in the Mekong and Ha Long Bay caves',
          'Imperial Citadel of Hue and Temple of Literature only',
          'Sapa terrace fields and Cu Chi tunnels'
        ],
        correctAnswer: 'Water puppetry in the Red River Delta and the ancient town of Hoi An',
        explanation: 'Đoạn 1 nêu: "From the water puppetry theatres of the Red River Delta to the UNESCO-recognized ancient town of Hoi An..."',
        evidenceQuote: 'water puppetry theatres of the Red River Delta to the UNESCO-recognized ancient town of Hoi An',
      },
      {
        id: 'q-read5-3',
        questionOrder: 3,
        questionText: 'What challenge is confronting traditional craft villages due to rapid urbanization?',
        type: 'multiple_choice',
        options: [
          'Younger generations migrate to metropolitan cities, leaving craft studios at risk of obsolescence',
          'Tourists are prohibited from visiting craft villages',
          'Raw materials like clay and silk are no longer available in Asia',
          'Government laws have outlawed handmade crafts'
        ],
        correctAnswer: 'Younger generations migrate to metropolitan cities, leaving craft studios at risk of obsolescence',
        explanation: 'Đoạn 2 nêu rõ người trẻ chuyển ra thành thị: "Many younger generations migrate toward metropolitan centers... leaving traditional studios in danger of obsolescence."',
        evidenceQuote: 'younger generations migrate toward metropolitan centers pursuing corporate careers, leaving traditional ceramic kilns',
      },
      {
        id: 'q-read5-4',
        questionOrder: 4,
        questionText: 'In paragraph 2, what does the word "obsolescence" mean?',
        type: 'multiple_choice',
        options: [
          'The state of being outdated or no longer used',
          'Rapid financial profitability',
          'Widespread international fame',
          'A celebration of national holidays'
        ],
        correctAnswer: 'The state of being outdated or no longer used',
        explanation: '"Obsolescence" nghĩa là tình trạng bị mai một, lỗi thời hoặc không còn được tiếp nối sử dụng.',
        evidenceQuote: 'leaving traditional ceramic kilns, silk weaving looms, and lacquerware studios in danger of obsolescence',
      },
      {
        id: 'q-read5-5',
        questionOrder: 5,
        questionText: 'True or False: Young artisans are combining traditional artisan skills with digital marketing and modern design.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Đoạn 3: "By combining authentic artisan techniques with modern digital marketing and eco-conscious design..."',
        evidenceQuote: 'combining authentic artisan techniques with modern digital marketing and eco-conscious design',
      },
      {
        id: 'q-read5-6',
        questionOrder: 6,
        questionText: 'True or False: According to the passage, Vietnamese cultural folklore has failed to reach any global audiences.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Đoạn 3 khẳng định những người trẻ tiên phong đang giới thiệu văn hóa dân gian Việt Nam ra thế giới: "...introducing Vietnamese folklore to global audiences while generating sustainable community income."',
        evidenceQuote: 'introducing Vietnamese folklore to global audiences while generating sustainable community income',
      },
      {
        id: 'q-read5-7',
        questionOrder: 7,
        questionText: 'What tone does the author maintain regarding the future of Vietnamese heritage?',
        type: 'multiple_choice',
        options: [
          'Encouraging and hopeful about youth-led cultural revitalization',
          'Pessimistic and resigned to complete cultural loss',
          'Aggressive and critical of all urban workers',
          'Indifferent and detached from societal changes'
        ],
        correctAnswer: 'Encouraging and hopeful about youth-led cultural revitalization',
        explanation: 'Tác giả mở đầu đoạn 3 bằng "Encouragingly" và đánh giá cao nỗ lực của các nghệ nhân trẻ, thể hiện tinh thần khích lệ và đầy hy vọng.',
        evidenceQuote: 'Encouragingly, a vibrant wave of youthful artisans and cultural tech innovators is revitalizing Vietnamese heritage',
      },
    ],
  },

  {
    id: 'ex-reading-6',
    title: 'The Evolution of Remote Work and Global Teams',
    topicId: 'career',
    topicTitle: 'Career & Workplace',
    level: 'Advanced',
    type: 'reading',
    passage: `The traditional paradigm of the eight-hour physical office day has undergone an irrevocable shift over the past decade. Catalyzed by ubiquitous cloud computing, high-speed broadband, and asynchronous collaboration platforms, remote and hybrid employment models have transitioned from progressive perks into organizational mainstays.

Proponents highlight considerable advantages: employees bypass exhausting daily commutes, reclaim autonomous control over their daily schedules, and enjoy greater proximity to their families. Simultaneously, enterprises can assemble geographically distributed talent across continents without being constrained by regional labor limitations.

Nonetheless, remote organizational culture introduces non-trivial complexities. The attenuation of spontaneous face-to-face exchanges can erode team cohesion and precipitate professional isolation. Furthermore, the blurring boundary between occupational duties and domestic life often fuels insidious burnout. Progressive companies are mitigating these pitfalls by formalizing asynchronous communication protocols and establishing deliberate "right to disconnect" policies.`,
    questions: [
      {
        id: 'q-read6-1',
        questionOrder: 1,
        questionText: 'What technological factors catalyzed the shift toward remote and hybrid work models?',
        type: 'multiple_choice',
        options: [
          'Ubiquitous cloud computing, high-speed broadband, and asynchronous collaboration tools',
          'The invention of mechanical typewriters and fax machines',
          'A decrease in international internet speeds',
          'The mandatory elimination of all computer screens'
        ],
        correctAnswer: 'Ubiquitous cloud computing, high-speed broadband, and asynchronous collaboration tools',
        explanation: 'Đoạn 1 nêu: "...Catalyzed by ubiquitous cloud computing, high-speed broadband, and asynchronous collaboration platforms..."',
        evidenceQuote: 'Catalyzed by ubiquitous cloud computing, high-speed broadband, and asynchronous collaboration platforms',
      },
      {
        id: 'q-read6-2',
        questionOrder: 2,
        questionText: 'According to paragraph 2, what major benefit do enterprises gain from distributed work?',
        type: 'multiple_choice',
        options: [
          'The ability to recruit talent across continents without regional geographic constraints',
          'Never needing to compensate workers with salaries',
          'Eliminating all forms of communication with staff',
          'Forcing all staff to live in the same time zone'
        ],
        correctAnswer: 'The ability to recruit talent across continents without regional geographic constraints',
        explanation: 'Đoạn 2: "...enterprises can assemble geographically distributed talent across continents without being constrained by regional labor limitations."',
        evidenceQuote: 'assemble geographically distributed talent across continents without being constrained by regional labor limitations',
      },
      {
        id: 'q-read6-3',
        questionOrder: 3,
        questionText: 'True or False: Remote work completely eliminates the risk of occupational burnout.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Đoạn 3 chỉ rõ việc ranh giới mờ nhạt giữa công việc và gia đình thường làm gia tăng kiệt sức: "...the blurring boundary between occupational duties and domestic life often fuels insidious burnout."',
        evidenceQuote: 'blurring boundary between occupational duties and domestic life often fuels insidious burnout',
      },
      {
        id: 'q-read6-4',
        questionOrder: 4,
        questionText: 'In paragraph 3, what does the word "attenuation" mean?',
        type: 'multiple_choice',
        options: [
          'Reduction or weakening of strength and frequency',
          'Massive multiplication in numbers',
          'Sudden violent confrontation',
          'Formal legal certification'
        ],
        correctAnswer: 'Reduction or weakening of strength and frequency',
        explanation: '"Attenuation" nghĩa là sự suy giảm, giảm bớt cường độ hoặc tần suất tiếp xúc trực tiếp.',
        evidenceQuote: 'attenuation of spontaneous face-to-face exchanges can erode team cohesion',
      },
      {
        id: 'q-read6-5',
        questionOrder: 5,
        questionText: 'How are forward-thinking organizations counteracting remote work burnout?',
        type: 'multiple_choice',
        options: [
          'By establishing asynchronous communication protocols and "right to disconnect" policies',
          'By installing 24-hour webcam surveillance on employees',
          'By banning vacations and weekend breaks completely',
          'By requiring employees to sleep inside physical offices'
        ],
        correctAnswer: 'By establishing asynchronous communication protocols and "right to disconnect" policies',
        explanation: 'Đoạn 3 nêu: "...formalizing asynchronous communication protocols and establishing deliberate \'right to disconnect\' policies."',
        evidenceQuote: 'establishing deliberate "right to disconnect" policies',
      },
      {
        id: 'q-read6-6',
        questionOrder: 6,
        questionText: 'True or False: Remote work allows workers to bypass exhausting daily commutes.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Đoạn 2 khẳng định: "...employees bypass exhausting daily commutes, reclaim autonomous control over their daily schedules..."',
        evidenceQuote: 'employees bypass exhausting daily commutes, reclaim autonomous control over their daily schedules',
      },
      {
        id: 'q-read6-7',
        questionOrder: 7,
        questionText: 'What is the central theme of the entire article?',
        type: 'multiple_choice',
        options: [
          'Remote work provides remarkable flexibility and global talent reach, but demands deliberate policies to prevent burnout',
          'Physical offices will completely disappear by tomorrow morning',
          'Remote work is solely beneficial for employers and detrimental to employees',
          'Asynchronous communication is useless for modern technology teams'
        ],
        correctAnswer: 'Remote work provides remarkable flexibility and global talent reach, but demands deliberate policies to prevent burnout',
        explanation: 'Bài viết phân tích đa chiều cả những ưu điểm vượt bậc (linh hoạt, tuyển dụng toàn cầu) lẫn các thách thức cần quản lý (cô lập, kiệt sức, ranh giới nghỉ ngơi).',
        evidenceQuote: 'Progressive companies are mitigating these pitfalls by formalizing asynchronous communication protocols',
      },
    ],
  },

  // 9. Listening Practice (Bài luyện nghe)
  {
    id: 'ex-listening-1',
    title: 'Planning a Weekend Trip to Ha Long Bay',
    topicId: 'travel',
    topicTitle: 'Travel',
    level: 'Intermediate',
    type: 'listening',
    transcript: `Hey Quan! Are you ready for our school excursion this Saturday? The tour bus will depart from our school gate at exactly 6:30 AM. Please make sure to arrive 15 minutes early. We will arrive at Ha Long Bay around 10:30 AM. Remember to pack a light jacket, your student ID, sunscreen, and a refillable water bottle. Lunch will be served on the cruise boat at 12:00 PM. We will visit the famous Sung Sot Cave in the afternoon and return home by 7:00 PM. It is going to be an unforgettable adventure!`,
    questions: [
      {
        id: 'q-list-1',
        questionOrder: 1,
        questionText: 'What time does the tour bus depart on Saturday morning?',
        type: 'multiple_choice',
        options: ['6:30 AM', '6:15 AM', '10:30 AM', '7:00 AM'],
        correctAnswer: '6:30 AM',
        explanation: 'Bài nghe nói: "The tour bus will depart from our school gate at exactly 6:30 AM."',
      },
      {
        id: 'q-list-2',
        questionOrder: 2,
        questionText: 'Where will lunch be served?',
        type: 'multiple_choice',
        options: ['On the cruise boat', 'At a restaurant on land', 'Inside the cave', 'At school'],
        correctAnswer: 'On the cruise boat',
        explanation: 'Người nói nêu rõ: "Lunch will be served on the cruise boat at 12:00 PM."',
      },
      {
        id: 'q-list-3',
        questionOrder: 3,
        questionText: 'Students are advised to arrive 15 minutes before the departure time.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Người nói dặn: "Please make sure to arrive 15 minutes early."',
      },
      {
        id: 'q-list-4',
        questionOrder: 4,
        questionText: 'Approximately what time will the tour bus arrive at Ha Long Bay?',
        type: 'multiple_choice',
        options: ['Around 10:30 AM', 'At 6:30 AM', 'At 12:00 PM', 'At 7:00 PM'],
        correctAnswer: 'Around 10:30 AM',
        explanation: 'Bài nghe thông báo: "We will arrive at Ha Long Bay around 10:30 AM."',
      },
      {
        id: 'q-list-5',
        questionOrder: 5,
        questionText: 'Which item is NOT mentioned on the student packing checklist?',
        type: 'multiple_choice',
        options: ['A heavy winter coat', 'A light jacket', 'Sunscreen', 'A refillable water bottle'],
        correctAnswer: 'A heavy winter coat',
        explanation: 'Bài nghe dặn mang áo khoác nhẹ ("a light jacket"), kem chống nắng ("sunscreen") và bình nước, không đề cập đến áo khoác mùa đông dày.',
      },
      {
        id: 'q-list-6',
        questionOrder: 6,
        questionText: 'True or False: The group will visit Sung Sot Cave in the morning before lunch.',
        type: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Bài nghe nói chuyến tham quan hang Sửng Sốt diễn ra vào buổi chiều: "We will visit the famous Sung Sot Cave in the afternoon..."',
      },
    ],
  },

  // 10. Speaking Challenge
  {
    id: 'ex-speak-1',
    title: 'Interactive Speaking Challenge: Life & Ambitions',
    topicId: 'hobbies',
    topicTitle: 'Hobbies',
    level: 'Intermediate',
    type: 'speaking',
    questions: [
      {
        id: 'q-speak-1',
        questionOrder: 1,
        questionText: 'Speak for 30-45 seconds about: "What is your favorite hobby and why do you enjoy it?"',
        type: 'speaking',
        correctAnswer: 'Any well-structured 3-4 sentence English response expressing hobby, frequency, and personal feelings.',
        explanation: 'Nói rõ tên sở thích, bạn bắt đầu từ khi nào, thường chơi với ai và cảm xúc mang lại.',
        hint: 'Gợi ý mở đầu: "My favorite hobby is playing basketball because it keeps me energetic and healthy..."',
      },
      {
        id: 'q-speak-2',
        questionOrder: 2,
        questionText: 'Speak for 30-45 seconds about: "Describe an unforgettable trip or vacation you experienced with family or friends."',
        type: 'speaking',
        correctAnswer: 'A coherent English monologue detailing location, activities, and memorable highlights.',
        explanation: 'Nêu địa điểm du lịch, thời gian, phương tiện di chuyển, món ăn đáng nhớ và lý do bạn yêu thích chuyến đi đó.',
        hint: 'Bắt đầu bằng: "Last summer, I had an unforgettable vacation to Da Nang with my family..."',
      },
      {
        id: 'q-speak-3',
        questionOrder: 3,
        questionText: 'Speak for 30-45 seconds about: "Who is a person you admire the most in your life, and why do they inspire you?"',
        type: 'speaking',
        correctAnswer: 'A descriptive response discussing character traits, achievements, and impact on the speaker.',
        explanation: 'Giới thiệu người bạn ngưỡng mộ (bố mẹ, thầy cô, bạn thân, danh nhân), phẩm chất tốt đẹp và bài học bạn học được từ họ.',
        hint: 'Bắt đầu bằng: "The person I look up to the most is my English teacher because of her dedication..."',
      },
      {
        id: 'q-speak-4',
        questionOrder: 4,
        questionText: 'Speak for 30-45 seconds about: "What is your dream career, and how will English skills empower you to succeed?"',
        type: 'speaking',
        correctAnswer: 'A visionary response connecting career goals with English communication capabilities.',
        explanation: 'Nói về nghề nghiệp tương lai mơ ước của bạn và cách tiếng Anh giúp bạn tiếp cận tài liệu quốc tế và cơ hội việc làm toàn cầu.',
        hint: 'Bắt đầu bằng: "In the future, I aspire to become a software engineer, and mastering English will enable me to..."',
      },
    ],
  },
];

// Dữ liệu mẫu Lịch sử học tập (Populated Learning History)
export const SEED_LEARNING_HISTORY: LearningHistoryRecord[] = [
  {
    id: 'hist-1',
    activityType: 'Speaking',
    topicId: 'introduce-yourself',
    topicTitle: 'Introduce yourself',
    level: 'Intermediate',
    score: 92,
    durationSeconds: 320,
    skillCategory: 'Speaking',
    detailsSummary: 'Luyện nói 5 lượt với AI. Phát âm tự nhiên, ngữ pháp thì hiện tại đơn tốt.',
    createdAt: '2026-10-02T14:30:00Z',
    speakingFeedback: [
      {
        pronunciationScore: 92,
        grammarScore: 90,
        vocabularyScore: 88,
        fluencyScore: 94,
        relevanceScore: 96,
        overallScore: 92,
        studentSentence: "Hello teacher, my name is Quan and I am fifteen years old. I live in Hanoi.",
        errors: [],
        correctedSentence: "Hello teacher, my name is Quan and I am fifteen years old. I live in Hanoi.",
        betterExpression: "Hi there! I'm Quan, a fifteen-year-old student currently residing in Hanoi.",
        recommendedVocab: ["residing", "passionate", "hometown"],
        pronunciationTips: "Good rhythm! Keep linking 'live in' smoothly.",
      }
    ],
  },
  {
    id: 'hist-2',
    activityType: 'Exercise',
    topicId: 'school',
    topicTitle: 'School Life & Present Tenses',
    level: 'Intermediate',
    score: 100,
    durationSeconds: 240,
    skillCategory: 'Grammar',
    detailsSummary: 'Hoàn thành bài tập trắc nghiệm ngữ pháp 4/4 câu đúng.',
    createdAt: '2026-10-02T10:15:00Z',
  },
  {
    id: 'hist-3',
    activityType: 'Listening',
    topicId: 'travel',
    topicTitle: 'Planning a Weekend Trip to Ha Long Bay',
    level: 'Intermediate',
    score: 100,
    durationSeconds: 410,
    skillCategory: 'Listening',
    detailsSummary: 'Nghe audio tốc độ 1x và trả lời chính xác 3/3 câu hỏi chi tiết.',
    createdAt: '2026-10-01T16:20:00Z',
  },
  {
    id: 'hist-4',
    activityType: 'RolePlay',
    topicId: 'rp-restaurant',
    topicTitle: 'At a Restaurant',
    level: 'Intermediate',
    score: 88,
    durationSeconds: 520,
    skillCategory: 'Speaking',
    detailsSummary: 'Đóng vai thực khách gọi món ăn và hỏi hóa đơn với nhân viên phục vụ AI.',
    createdAt: '2026-09-30T19:40:00Z',
  },
  {
    id: 'hist-5',
    activityType: 'Reading',
    topicId: 'technology',
    topicTitle: 'The Rise of AI in Education',
    level: 'Advanced',
    score: 85,
    durationSeconds: 480,
    skillCategory: 'Reading',
    detailsSummary: 'Đọc hiểu văn bản học thuật và suy luận từ vựng theo ngữ cảnh.',
    createdAt: '2026-09-29T15:10:00Z',
  },
  {
    id: 'hist-6',
    activityType: 'FillBlank',
    topicId: 'health',
    topicTitle: 'Daily Morning Routine Cloze',
    level: 'Beginner',
    score: 95,
    durationSeconds: 180,
    skillCategory: 'Vocabulary',
    detailsSummary: 'Điền chính xác các từ vựng về sinh hoạt buổi sáng.',
    createdAt: '2026-09-28T09:00:00Z',
  },
  {
    id: 'hist-7',
    activityType: 'Exercise',
    topicId: 'at-airport',
    topicTitle: 'Travel & Airport Vocabulary Matching',
    level: 'Intermediate',
    score: 90,
    durationSeconds: 210,
    skillCategory: 'Vocabulary',
    detailsSummary: 'Nối chuẩn 4 cặp từ vựng chuyên ngành sân bay.',
    createdAt: '2026-09-27T17:30:00Z',
  },
  {
    id: 'hist-8',
    activityType: 'Speaking',
    topicId: 'hobbies',
    topicTitle: 'Hobbies & Passions',
    level: 'Beginner',
    score: 84,
    durationSeconds: 360,
    skillCategory: 'Speaking',
    detailsSummary: 'Luyện nói về sở thích bóng rổ và âm nhạc.',
    createdAt: '2026-09-26T20:10:00Z',
  },
];

// Dữ liệu thống kê theo ngày (Daily Statistics phục vụ Biểu đồ)
export const SEED_DAILY_STATS: DailyStatisticRecord[] = [
  {
    date: '2026-09-26',
    dayLabel: 'T7 (26/9)',
    totalMinutes: 28,
    completedLessons: 2,
    averageScore: 84,
    speakingScore: 84,
    listeningScore: 80,
    readingScore: 82,
    grammarScore: 85,
    vocabularyScore: 82,
    correctAnswers: 8,
    incorrectAnswers: 2,
    speakingSessionsCount: 1,
    listeningLessonsCount: 1,
  },
  {
    date: '2026-09-27',
    dayLabel: 'CN (27/9)',
    totalMinutes: 35,
    completedLessons: 3,
    averageScore: 90,
    speakingScore: 88,
    listeningScore: 92,
    readingScore: 88,
    grammarScore: 90,
    vocabularyScore: 90,
    correctAnswers: 12,
    incorrectAnswers: 1,
    speakingSessionsCount: 1,
    listeningLessonsCount: 1,
  },
  {
    date: '2026-09-28',
    dayLabel: 'T2 (28/9)',
    totalMinutes: 25,
    completedLessons: 2,
    averageScore: 87,
    speakingScore: 85,
    listeningScore: 86,
    readingScore: 90,
    grammarScore: 88,
    vocabularyScore: 95,
    correctAnswers: 9,
    incorrectAnswers: 2,
    speakingSessionsCount: 1,
    listeningLessonsCount: 0,
  },
  {
    date: '2026-09-29',
    dayLabel: 'T3 (29/9)',
    totalMinutes: 42,
    completedLessons: 4,
    averageScore: 85,
    speakingScore: 82,
    listeningScore: 88,
    readingScore: 85,
    grammarScore: 89,
    vocabularyScore: 87,
    correctAnswers: 15,
    incorrectAnswers: 3,
    speakingSessionsCount: 2,
    listeningLessonsCount: 1,
  },
  {
    date: '2026-09-30',
    dayLabel: 'T4 (30/9)',
    totalMinutes: 38,
    completedLessons: 3,
    averageScore: 91,
    speakingScore: 88,
    listeningScore: 93,
    readingScore: 92,
    grammarScore: 90,
    vocabularyScore: 91,
    correctAnswers: 14,
    incorrectAnswers: 1,
    speakingSessionsCount: 1,
    listeningLessonsCount: 1,
  },
  {
    date: '2026-10-01',
    dayLabel: 'T5 (01/10)',
    totalMinutes: 40,
    completedLessons: 3,
    averageScore: 94,
    speakingScore: 90,
    listeningScore: 100,
    readingScore: 94,
    grammarScore: 92,
    vocabularyScore: 93,
    correctAnswers: 16,
    incorrectAnswers: 0,
    speakingSessionsCount: 1,
    listeningLessonsCount: 1,
  },
  {
    date: '2026-10-02',
    dayLabel: 'Hôm nay (02/10)',
    totalMinutes: 45,
    completedLessons: 4,
    averageScore: 96,
    speakingScore: 92,
    listeningScore: 95,
    readingScore: 95,
    grammarScore: 100,
    vocabularyScore: 96,
    correctAnswers: 18,
    incorrectAnswers: 1,
    speakingSessionsCount: 2,
    listeningLessonsCount: 1,
  },
];
